[package]
name = "xondemoparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
nu-pretty-hex = "0.61.0"
num_enum = "0.5.7"
